// Mapa completo de países com aliases em português e inglês
export const COUNTRY_MAP: { [key: string]: string } = {
  // A
  'afeganistão': 'Afghanistan',
  'afghanistan': 'Afghanistan',
  'albânia': 'Albania',
  'albania': 'Albania',
  'argélia': 'Algeria',
  'algeria': 'Algeria',
  'andorra': 'Andorra',
  'angola': 'Angola',
  'anguila': 'Anguilla',
  'anguilla': 'Anguilla',
  'antígua e barbuda': 'Antigua and Barbuda',
  'antigua and barbuda': 'Antigua and Barbuda',
  'arábia saudita': 'Saudi Arabia',
  'saudi arabia': 'Saudi Arabia',
  'argélia': 'Algeria',
  'argentina': 'Argentina',
  'armênia': 'Armenia',
  'armenia': 'Armenia',
  'aruba': 'Aruba',
  'austrália': 'Australia',
  'australia': 'Australia',
  'áustria': 'Austria',
  'austria': 'Austria',
  'azerbaijão': 'Azerbaijan',
  'azerbaijan': 'Azerbaijan',

  // B
  'bahamas': 'Bahamas',
  'bahrein': 'Bahrain',
  'bahrain': 'Bahrain',
  'bangladesh': 'Bangladesh',
  'barbados': 'Barbados',
  'bélgica': 'Belgium',
  'belgium': 'Belgium',
  'belize': 'Belize',
  'benin': 'Benin',
  'bermudas': 'Bermuda',
  'bermuda': 'Bermuda',
  'bielorrússia': 'Belarus',
  'belarus': 'Belarus',
  'birmânia': 'Myanmar',
  'myanmar': 'Myanmar',
  'bolívia': 'Bolivia',
  'bolivia': 'Bolivia',
  'bósnia e herzegovina': 'Bosnia and Herzegovina',
  'bosnia and herzegovina': 'Bosnia and Herzegovina',
  'botsuana': 'Botswana',
  'botswana': 'Botswana',
  'brasil': 'Brazil',
  'brazil': 'Brazil',
  'brunei': 'Brunei',
  'bulgária': 'Bulgaria',
  'bulgaria': 'Bulgaria',
  'burquina faso': 'Burkina Faso',
  'burkina faso': 'Burkina Faso',
  'burundi': 'Burundi',

  // C
  'cabo verde': 'Cape Verde',
  'cape verde': 'Cape Verde',
  'camboja': 'Cambodia',
  'cambodia': 'Cambodia',
  'camarões': 'Cameroon',
  'cameroon': 'Cameroon',
  'canadá': 'Canada',
  'canada': 'Canada',
  'catar': 'Qatar',
  'qatar': 'Qatar',
  'cazaquistão': 'Kazakhstan',
  'kazakhstan': 'Kazakhstan',
  'chade': 'Chad',
  'chad': 'Chad',
  'chile': 'Chile',
  'china': 'China',
  'chipre': 'Cyprus',
  'cyprus': 'Cyprus',
  'cingapura': 'Singapore',
  'singapore': 'Singapore',
  'colômbia': 'Colombia',
  'colombia': 'Colombia',
  'comores': 'Comoros',
  'comoros': 'Comoros',
  'congo': 'Congo',
  'coreia do norte': 'North Korea',
  'north korea': 'North Korea',
  'coreia do sul': 'South Korea',
  'south korea': 'South Korea',
  'costa do marfim': 'Ivory Coast',
  'ivory coast': 'Ivory Coast',
  'costa rica': 'Costa Rica',
  'croácia': 'Croatia',
  'croatia': 'Croatia',
  'cuba': 'Cuba',

  // D
  'dinamarca': 'Denmark',
  'denmark': 'Denmark',
  'djibuti': 'Djibouti',
  'djibouti': 'Djibouti',
  'dominica': 'Dominica',
  'república dominicana': 'Dominican Republic',
  'dominican republic': 'Dominican Republic',

  // E
  'egito': 'Egypt',
  'egypt': 'Egypt',
  'emirados árabes unidos': 'United Arab Emirates',
  'united arab emirates': 'United Arab Emirates',
  'uae': 'United Arab Emirates',
  'equador': 'Ecuador',
  'ecuador': 'Ecuador',
  'eritreia': 'Eritrea',
  'eritrea': 'Eritrea',
  'eslováquia': 'Slovakia',
  'slovakia': 'Slovakia',
  'eslovênia': 'Slovenia',
  'slovenia': 'Slovenia',
  'espanha': 'Spain',
  'spain': 'Spain',
  'estados unidos': 'United States',
  'united states': 'United States',
  'eua': 'United States',
  'usa': 'United States',
  'us': 'United States',
  'estônia': 'Estonia',
  'estonia': 'Estonia',
  'etiópia': 'Ethiopia',
  'ethiopia': 'Ethiopia',

  // F
  'fiji': 'Fiji',
  'filipinas': 'Philippines',
  'philippines': 'Philippines',
  'finlândia': 'Finland',
  'finland': 'Finland',
  'frança': 'France',
  'france': 'France',
  'gabão': 'Gabon',
  'gabon': 'Gabon',
  'alemanha': 'Germany',
  'germany': 'Germany',
  'gâmbia': 'Gambia',
  'gambia': 'Gambia',
  'gana': 'Ghana',
  'ghana': 'Ghana',
  'geórgia': 'Georgia',
  'georgia': 'Georgia',
  'gibraltar': 'Gibraltar',
  'granada': 'Grenada',
  'grenada': 'Grenada',
  'grécia': 'Greece',
  'greece': 'Greece',
  'groenlândia': 'Greenland',
  'greenland': 'Greenland',
  'guadeloupe': 'Guadeloupe',
  'guam': 'Guam',
  'guatemala': 'Guatemala',
  'guernsey': 'Guernsey',
  'guiana': 'Guyana',
  'guyana': 'Guyana',
  'guiana francesa': 'French Guiana',
  'french guiana': 'French Guiana',
  'guiné': 'Guinea',
  'guinea': 'Guinea',
  'guiné equatorial': 'Equatorial Guinea',
  'equatorial guinea': 'Equatorial Guinea',
  'guiné-bissau': 'Guinea-Bissau',
  'guinea-bissau': 'Guinea-Bissau',

  // H
  'haiti': 'Haiti',
  'honduras': 'Honduras',
  'hong kong': 'Hong Kong',
  'hungria': 'Hungary',
  'hungary': 'Hungary',

  // I
  'iêmen': 'Yemen',
  'yemen': 'Yemen',
  'ilhas aland': 'Aland Islands',
  'aland islands': 'Aland Islands',
  'ilhas cayman': 'Cayman Islands',
  'cayman islands': 'Cayman Islands',
  'ilhas cocos': 'Cocos Islands',
  'cocos islands': 'Cocos Islands',
  'ilhas cook': 'Cook Islands',
  'cook islands': 'Cook Islands',
  'ilhas faroe': 'Faroe Islands',
  'faroe islands': 'Faroe Islands',
  'ilhas heard': 'Heard Island',
  'heard island': 'Heard Island',
  'ilhas malvinas': 'Falkland Islands',
  'falkland islands': 'Falkland Islands',
  'ilhas mariana': 'Northern Mariana Islands',
  'northern mariana islands': 'Northern Mariana Islands',
  'ilhas marshall': 'Marshall Islands',
  'marshall islands': 'Marshall Islands',
  'ilhas menores': 'Minor Islands',
  'minor islands': 'Minor Islands',
  'ilhas norfolk': 'Norfolk Island',
  'norfolk island': 'Norfolk Island',
  'ilhas salomão': 'Solomon Islands',
  'solomon islands': 'Solomon Islands',
  'ilhas turcos e caicos': 'Turks and Caicos Islands',
  'turks and caicos islands': 'Turks and Caicos Islands',
  'ilhas virgens britânicas': 'British Virgin Islands',
  'british virgin islands': 'British Virgin Islands',
  'ilhas virgens americanas': 'US Virgin Islands',
  'us virgin islands': 'US Virgin Islands',
  'índia': 'India',
  'india': 'India',
  'indonésia': 'Indonesia',
  'indonesia': 'Indonesia',
  'irã': 'Iran',
  'iran': 'Iran',
  'iraque': 'Iraq',
  'iraq': 'Iraq',
  'irlanda': 'Ireland',
  'ireland': 'Ireland',
  'irlanda do norte': 'Northern Ireland',
  'northern ireland': 'Northern Ireland',
  'islândia': 'Iceland',
  'iceland': 'Iceland',
  'israel': 'Israel',
  'itália': 'Italy',
  'italy': 'Italy',

  // J
  'jamaica': 'Jamaica',
  'japão': 'Japan',
  'japan': 'Japan',
  'jersey': 'Jersey',
  'jordânia': 'Jordan',
  'jordan': 'Jordan',

  // K
  'kuwait': 'Kuwait',
  'quirguistão': 'Kyrgyzstan',
  'kyrgyzstan': 'Kyrgyzstan',

  // L
  'laos': 'Laos',
  'lesoto': 'Lesotho',
  'lesotho': 'Lesotho',
  'letônia': 'Latvia',
  'latvia': 'Latvia',
  'líbano': 'Lebanon',
  'lebanon': 'Lebanon',
  'libéria': 'Liberia',
  'liberia': 'Liberia',
  'líbia': 'Libya',
  'libya': 'Libya',
  'liechtenstein': 'Liechtenstein',
  'lituânia': 'Lithuania',
  'lithuania': 'Lithuania',
  'luxemburgo': 'Luxembourg',
  'luxembourg': 'Luxembourg',

  // M
  'macau': 'Macau',
  'macedônia': 'North Macedonia',
  'north macedonia': 'North Macedonia',
  'madagascar': 'Madagascar',
  'malásia': 'Malaysia',
  'malaysia': 'Malaysia',
  'malawi': 'Malawi',
  'maldivas': 'Maldives',
  'maldives': 'Maldives',
  'mali': 'Mali',
  'malta': 'Malta',
  'marrocos': 'Morocco',
  'morocco': 'Morocco',
  'martinica': 'Martinique',
  'mauritânia': 'Mauritania',
  'mauritania': 'Mauritania',
  'maurício': 'Mauritius',
  'mauritius': 'Mauritius',
  'méxico': 'Mexico',
  'mexico': 'Mexico',
  'micronésia': 'Micronesia',
  'micronesia': 'Micronesia',
  'moçambique': 'Mozambique',
  'mozambique': 'Mozambique',
  'moldávia': 'Moldova',
  'moldova': 'Moldova',
  'mônaco': 'Monaco',
  'monaco': 'Monaco',
  'mongólia': 'Mongolia',
  'mongolia': 'Mongolia',
  'montenegro': 'Montenegro',
  'montserrat': 'Montserrat',
  'myanmar': 'Myanmar',

  // N
  'namíbia': 'Namibia',
  'namibia': 'Namibia',
  'nauru': 'Nauru',
  'nepal': 'Nepal',
  'nicarágua': 'Nicaragua',
  'nicaragua': 'Nicaragua',
  'niger': 'Niger',
  'nigéria': 'Nigeria',
  'nigeria': 'Nigeria',
  'niue': 'Niue',
  'noruega': 'Norway',
  'norway': 'Norway',
  'nova caledônia': 'New Caledonia',
  'new caledonia': 'New Caledonia',
  'nova zelândia': 'New Zealand',
  'new zealand': 'New Zealand',

  // O
  'omã': 'Oman',
  'oman': 'Oman',

  // P
  'paquistão': 'Pakistan',
  'pakistan': 'Pakistan',
  'palau': 'Palau',
  'palestina': 'Palestine',
  'palestine': 'Palestine',
  'panamá': 'Panama',
  'panama': 'Panama',
  'papua nova guiné': 'Papua New Guinea',
  'papua new guinea': 'Papua New Guinea',
  'paraguai': 'Paraguay',
  'paraguay': 'Paraguay',
  'peru': 'Peru',
  'polinésia francesa': 'French Polynesia',
  'french polynesia': 'French Polynesia',
  'polônia': 'Poland',
  'poland': 'Poland',
  'porto rico': 'Puerto Rico',
  'puerto rico': 'Puerto Rico',
  'portugal': 'Portugal',
  'príncipe e são tomé': 'Sao Tome and Principe',
  'sao tome and principe': 'Sao Tome and Principe',

  // Q
  'quênia': 'Kenya',
  'kenya': 'Kenya',

  // R
  'reino unido': 'United Kingdom',
  'united kingdom': 'United Kingdom',
  'uk': 'United Kingdom',
  'gb': 'United Kingdom',
  'república centro-africana': 'Central African Republic',
  'central african republic': 'Central African Republic',
  'república checa': 'Czech Republic',
  'czech republic': 'Czech Republic',
  'república democrática do congo': 'Democratic Republic of the Congo',
  'democratic republic of the congo': 'Democratic Republic of the Congo',
  'república do congo': 'Republic of the Congo',
  'republic of the congo': 'Republic of the Congo',
  'república dominicana': 'Dominican Republic',
  'dominican republic': 'Dominican Republic',
  'reunião': 'Reunion',
  'reunion': 'Reunion',
  'romênia': 'Romania',
  'romania': 'Romania',
  'ruanda': 'Rwanda',
  'rwanda': 'Rwanda',
  'rússia': 'Russia',
  'russia': 'Russia',

  // S
  'saara ocidental': 'Western Sahara',
  'western sahara': 'Western Sahara',
  'samoa': 'Samoa',
  'samoa americana': 'American Samoa',
  'american samoa': 'American Samoa',
  'san marino': 'San Marino',
  'santa helena': 'Saint Helena',
  'saint helena': 'Saint Helena',
  'santa lúcia': 'Saint Lucia',
  'saint lucia': 'Saint Lucia',
  'santo andré e nevis': 'Saint Kitts and Nevis',
  'saint kitts and nevis': 'Saint Kitts and Nevis',
  'são bartolomeu': 'Saint Barthelemy',
  'saint barthelemy': 'Saint Barthelemy',
  'são cristóvão e nevis': 'Saint Kitts and Nevis',
  'são marinho': 'San Marino',
  'são martim': 'Saint Martin',
  'saint martin': 'Saint Martin',
  'são paulo': 'Sao Paulo',
  'são tomé e príncipe': 'Sao Tome and Principe',
  'sao tome and principe': 'Sao Tome and Principe',
  'são vicente e granadinas': 'Saint Vincent and the Grenadines',
  'saint vincent and the grenadines': 'Saint Vincent and the Grenadines',
  'seicheles': 'Seychelles',
  'seychelles': 'Seychelles',
  'senegal': 'Senegal',
  'serra leoa': 'Sierra Leone',
  'sierra leone': 'Sierra Leone',
  'sérvia': 'Serbia',
  'serbia': 'Serbia',
  'singapura': 'Singapore',
  'singapore': 'Singapore',
  'síria': 'Syria',
  'syria': 'Syria',
  'somália': 'Somalia',
  'somalia': 'Somalia',
  'sri lanca': 'Sri Lanka',
  'sri lanka': 'Sri Lanka',
  'suazilândia': 'Eswatini',
  'eswatini': 'Eswatini',
  'sudão': 'Sudan',
  'sudan': 'Sudan',
  'sudão do sul': 'South Sudan',
  'south sudan': 'South Sudan',
  'suécia': 'Sweden',
  'sweden': 'Sweden',
  'suíça': 'Switzerland',
  'switzerland': 'Switzerland',
  'surinã': 'Suriname',
  'suriname': 'Suriname',

  // T
  'tailândia': 'Thailand',
  'thailand': 'Thailand',
  'taiwan': 'Taiwan',
  'tajiquistão': 'Tajikistan',
  'tajikistan': 'Tajikistan',
  'tanzânia': 'Tanzania',
  'tanzania': 'Tanzania',
  'tcheca': 'Czech Republic',
  'timor-leste': 'Timor-Leste',
  'timor leste': 'Timor-Leste',
  'togo': 'Togo',
  'tonga': 'Tonga',
  'trinidad e tobago': 'Trinidad and Tobago',
  'trinidad and tobago': 'Trinidad and Tobago',
  'tunísia': 'Tunisia',
  'tunisia': 'Tunisia',
  'turcomênia': 'Turkmenistan',
  'turkmenistan': 'Turkmenistan',
  'turquia': 'Turkey',
  'turkey': 'Turkey',
  'tuvalu': 'Tuvalu',

  // U
  'uganda': 'Uganda',
  'ucrânia': 'Ukraine',
  'ukraine': 'Ukraine',
  'uruguai': 'Uruguay',
  'uruguay': 'Uruguay',
  'uzbequistão': 'Uzbekistan',
  'uzbekistan': 'Uzbekistan',

  // V
  'vanuatu': 'Vanuatu',
  'vaticano': 'Vatican City',
  'vatican city': 'Vatican City',
  'venezuela': 'Venezuela',
  'vietnã': 'Vietnam',
  'vietnam': 'Vietnam',

  // W
  'wallis e futuna': 'Wallis and Futuna',
  'wallis and futuna': 'Wallis and Futuna',

  // Z
  'zâmbia': 'Zambia',
  'zambia': 'Zambia',
  'zimbábue': 'Zimbabwe',
  'zimbabwe': 'Zimbabwe',
};

export const normalizeCountry = (input: string): string | null => {
  const normalized = input.toLowerCase().trim();
  return COUNTRY_MAP[normalized] || null;
};

export const extractCountryFromQuery = (query: string): string | null => {
  const queryLower = query.toLowerCase();
  
  // Ordenar por comprimento decrescente para evitar matches parciais
  const sortedKeys = Object.keys(COUNTRY_MAP).sort((a, b) => b.length - a.length);
  
  for (const key of sortedKeys) {
    if (queryLower.includes(key)) {
      return COUNTRY_MAP[key];
    }
  }
  return null;
};
